In [1]:
import pandas as pd

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.

In [43]:
police = pd.read_csv(r'/Users/ashahwaka/Downloads/police.csv')

In [44]:
police.head()

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,1/2/2005,1:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,1/18/2005,8:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,1/23/2005,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2/20/2005,17:15,NaN,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,3/14/2005,10:00,NaN,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [45]:
police

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,1/2/2005,1:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,1/18/2005,8:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,1/23/2005,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2/20/2005,17:15,NaN,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,3/14/2005,10:00,NaN,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65530,12/6/2012,17:54,NaN,F,1987.0,25.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
65531,12/6/2012,22:22,NaN,M,1954.0,58.0,White,Speeding,Speeding,False,NaN,Warning,False,0-15 Min,False
65532,12/6/2012,23:20,NaN,M,1985.0,27.0,Black,Equipment/Inspection Violation,Equipment,False,NaN,Citation,False,0-15 Min,False
65533,12/7/2012,0:23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,False
65534,12/7/2012,0:30,NaN,F,1985.0,27.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

# remove the columns that contain missing values

In [46]:
police.isnull().sum()

stop_date                 0
stop_time                 0
country_name          65535
driver_gender          4061
driver_age_raw         4054
driver_age             4307
driver_race            4060
violation_raw          4060
violation              4060
search_conducted          0
search_type           63056
stop_outcome           4060
is_arrested            4060
stop_duration          4060
drugs_related_stop        0
dtype: int64

In [10]:
police.drop(columns = 'country_name',inplace=True)

In [11]:
police.isnull().sum()

stop_date                 0
stop_time                 0
driver_gender          4061
driver_age_raw         4054
driver_age             4307
driver_race            4060
violation_raw          4060
violation              4060
search_conducted          0
search_type           63056
stop_outcome           4060
is_arrested            4060
stop_duration          4060
drugs_related_stop        0
dtype: int64

# for speeding, were men or women stopped more often?

In [47]:
police.head(2)

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,1/2/2005,1:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,1/18/2005,8:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [15]:
police[police.violation == 'Speeding'].driver_gender.value_counts()

driver_gender
M    25517
F    11686
Name: count, dtype: int64

# Does gender affect who gets searched during a stop

In [48]:
police.head()

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,1/2/2005,1:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,1/18/2005,8:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,1/23/2005,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2/20/2005,17:15,NaN,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,3/14/2005,10:00,NaN,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [49]:
police.groupby('driver_gender').search_conducted.sum()

driver_gender
F     366
M    2113
Name: search_conducted, dtype: int64

# what is the mean stop_duration

In [50]:
police.head()

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,1/2/2005,1:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,1/18/2005,8:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,1/23/2005,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2/20/2005,17:15,NaN,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,3/14/2005,10:00,NaN,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [51]:
# convert the values
police.stop_duration.value_counts()

stop_duration
0-15 Min     47379
16-30 Min    11448
30+ Min       2647
2                1
Name: count, dtype: int64

In [53]:
unmapped = police['stop_duration'].isna()

In [54]:
unmapped.head()

0    False
1    False
2    False
3    False
4    False
Name: stop_duration, dtype: bool

In [55]:
police['stop_duration'] = police['stop_duration'].map({'0-15 Min' : 7.5, '16-30 Min': 23, '30+ Min': 45})

In [56]:
police

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,1/2/2005,1:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False
1,1/18/2005,8:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False
2,1/23/2005,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False
3,2/20/2005,17:15,NaN,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,23.0,False
4,3/14/2005,10:00,NaN,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65530,12/6/2012,17:54,NaN,F,1987.0,25.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False
65531,12/6/2012,22:22,NaN,M,1954.0,58.0,White,Speeding,Speeding,False,NaN,Warning,False,7.5,False
65532,12/6/2012,23:20,NaN,M,1985.0,27.0,Black,Equipment/Inspection Violation,Equipment,False,NaN,Citation,False,7.5,False
65533,12/7/2012,0:23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,False
65534,12/7/2012,0:30,NaN,F,1985.0,27.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False

In [57]:
police.head(50)

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,1/2/2005,1:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False
1,1/18/2005,8:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False
2,1/23/2005,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False
3,2/20/2005,17:15,NaN,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,23.0,False
4,3/14/2005,10:00,NaN,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False
5,3/23/2005,9:45,NaN,M,1982.0,23.0,Black,Equipment/Inspection Violation,Equipment,False,NaN,Citation,False,7.5,False
6,4/1/2005,17:30,NaN,M,1969.0,36.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False
7,6/6/2005,13:20,NaN,F,1986.0,19.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False
8,7/13/2005,10:15,NaN,M,1970.0,35.0,Black,Speeding,Speeding,False,NaN,Citation,False,7.5,False
9,7/13/2005,15:45,NaN,M,1970.0,35.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False
10,7/13/2005,16:20,NaN,M,1979.0,26.0,Asian,Speeding,Speeding,False,NaN,Citation,False,7.5,False
11,7/13/2005,19:00,NaN,F,1966.0,39.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False
12,7/14/2005,19:55,NaN,M,1979.0,26.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False
13,7/18/2005,19:30,NaN,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False
14,7/18/2005,19:45,NaN,M,1969.0,36.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False
15,7/19/2005,0:30,NaN,M,1982.0,23.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False
16,7/19/2005,0:30,NaN,M,1982.0,23.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False
17,7/19/2005,23:30,NaN,M,1979.0,26.0,White,Equipment/Inspection Violation,Equipment,False,NaN,Citation,False,7.5,False
18,7/20/2005,0:05,NaN,M,1955.0,50.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False
19,7/24/2005,20:10,NaN,F,1958.0,47.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False
20,7/28/2005,12:37,NaN,F,1979.0,26.0,Asian,Speeding,Speeding,False,NaN,Citation,False,7.5,False
21,8/7/2005,16:50,NaN,M,1953.0,52.0,White,Other Traffic Violation,Moving violation,False,NaN,Citation,False,7.5,False
22,8/8/2005,2:09,NaN,M,1955.0,50.0,Black,Other Traffic Violation,Moving violation,False,NaN,Arrest Driver,True,45.0,False
23,8/18/2005,10:57,NaN,F,1967.0,38.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False
24,8/28/2005,1:00,NaN,M,1979.0,26.0,White,Other Traffic Violation,Moving violation,True,"Incident to Arrest,Protective Frisk",Arrest Driver,True,23.0,False
25,9/3/2005,16:02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,False
26,9/17/2005,10:54,NaN,M,1964.0,41.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False
27,9/21/2005,13:30,NaN,F,1977.0,28.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False
28,9/22/2005,22:34,NaN,M,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False
29,9/26/2005,1:05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,False
30,9/26/2005,12:09,NaN,M,1959.0,46.0,Black,Other Traffic Violation,Moving violation,False,NaN,Citation,False,45.0,False
31,9/28/2005,6:20,NaN,M,1982.0,23.0,White,Speeding,Speeding,False,NaN,Arrest Driver,True,23.0,False
32,9/28/2005,7:15,NaN,M,1973.0,32.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False
33,9/28/2005,7:45,NaN,M,1953.0,52.0,White,Other Traffic Violation,Moving violation,False,NaN,Citation,False,7.5,False
34,9/29/2005,23:45,NaN,M,1947.0,58.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False
35,9/30/2005,0:15,NaN,M,1978.0,27.0,White,Equipment/Inspection Violation,Equipment,False,NaN,N/D,False,7.5,False
36,9/30/2005,9:30,NaN,F,1986.0,19.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False
37,9/30/2005,14:00,NaN,M,1962.0,43.0,Asian,Speeding,Speeding,False,NaN,Citation,False,7.5,False
38,9/30/2005,19:25,NaN,M,1981.0,24.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False
39,9/30/2005,20:17,NaN,M,1988.0,17.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False
40,10/1/2005,0:00,NaN,M,1988.0,17.0,White,Equipment/Inspection Violation,Equipment,True,Probable Cause,Arrest Driver,True,23.0,True
41,10/1/2005,0:00,NaN,M,1988.0,17.0,White,Equipment/Inspection Violation,Equipment,True,Probable Cause,Citation,False,45.0,True
42,10/1/2005,0:50,NaN,M,1977.0,28.0,Hispanic,Other Traffic Violation,Moving violation,False,NaN,Arrest Driver,True,45.0,False
43,10/1/2005,1:00,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False
44,10/1/2005,1:45,NaN,M,1983.0,22.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False
45,10/1/2005,2:45,NaN,M,1961.0,44.0,White,Other Traffic Violation,Moving violation,False,NaN,Citation,False,7.5,False
46,10/1/2005,8:40,NaN,M,1959.0,46.0,White,Equipment/Inspection Violation,Equipment,False,NaN,Citation,False,7.5,False
47,10/1/2005,9:10,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False
48,10/1/2005,9:20,NaN,M,1957.0,48.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False
49,10/1/2005,10:45,NaN,M,1971.0,34.0,White,Equipment/Inspection Violation,Equipment,False,NaN,Citation,False,7.5,False

In [58]:
police.stop_duration.mean()

12.001195627419722

# Compare the age distributions for each violation

In [60]:
police.head(2)

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,1/2/2005,1:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False
1,1/18/2005,8:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,7.5,False

In [61]:
police.groupby('violation').driver_age.describe()

,count,mean,std,min,25%,50%,75%,max
violation,,,,,,,,
Equipment,6507.0,31.682957,11.380671,16.0,23.0,28.0,39.0,81.0
Moving violation,11876.0,36.736443,13.258350,15.0,25.0,35.0,47.0,86.0
Other,3477.0,40.362381,12.754423,16.0,30.0,41.0,50.0,86.0
Registration/plates,2240.0,32.656696,11.150780,16.0,24.0,30.0,40.0,74.0
Seat belt,3.0,30.333333,10.214369,23.0,24.5,26.0,34.0,42.0
Speeding,37120.0,33.262581,12.615781,15.0,23.0,30.0,42.0,88.0